## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('iot', ['internet', 'network', 'core'])
    module.includes = '.'
    module.source = [
        'model/iot-net-device.cc',
        'model/iot-header.cc',
        'helper/iot-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('iot')
    module_test.source = [
        'test/mock-net-device.cc',
        'test/iot-hc1-test.cc',
        'test/iot-iphc-test.cc',
        'test/iot-iphc-stateful-test.cc',
        'test/iot-fragmentation-test.cc',
        ]

    # This suite runs an example, only include if examples are built
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
            'test/iot-examples-test-suite.cc',
            ])
    
    headers = bld(features=['ns3header'])
    headers.module = 'iot'
    headers.source = [
        'model/iot-net-device.h',
        'model/iot-header.h',
        'helper/iot-helper.h',
        ]


    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')
   
    bld.ns3_python_bindings()
